type Incindet = {
  assignee: string | null;
  createdAt: string;
  updatedAt: string;
  checksData: string;
  id: string;
  status: string;
  title: string;
  tags: string;
  severity: number;
};

export const incidents: Incindet[] = [
  {
    assignee: null,
    createdAt: "2023-04-24T15:40:14.208Z",
    updatedAt: "2023-04-24T15:40:14.208Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgv08k5c0064010jnf8354ve",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T15:39:13.470Z",
    updatedAt: "2023-04-24T15:39:13.470Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgv079a6005n010j8tczzqxu",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T15:39:13.286Z",
    updatedAt: "2023-04-24T15:39:13.286Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clgv07952005g010j3r1it9fi",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T15:39:13.112Z",
    updatedAt: "2023-04-24T15:39:13.112Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgv079070059010jdtsq9gm6",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T15:39:12.930Z",
    updatedAt: "2023-04-24T15:39:12.930Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgv078v40052010jeb493aeu",
    status: "open",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: "obi.wan@redcarbon.ai",
    createdAt: "2023-04-24T14:54:35.310Z",
    updatedAt: "2023-04-24T14:54:35.310Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clguylust003i010jds1nns4f",
    status: "under_investigation",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: "obi.wan@redcarbon.ai",
    createdAt: "2023-04-24T14:54:34.810Z",
    updatedAt: "2023-04-24T14:54:34.810Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clguyluex003b010jg1pz32qv",
    status: "closed",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:34.210Z",
    updatedAt: "2023-04-24T14:54:34.210Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clguylty90034010jpivg4l6a",
    status: "open",
    title: "Look-alike Domain of demo.com registered",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:33.414Z",
    updatedAt: "2023-04-24T14:54:33.414Z",
    checksData:
      '{"done":18,"error":0,"loading":0,"pending":0,"total":18,"featureUnlicensed":0}',
    id: "clguyltc5002y010jc4ke305a",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:32.615Z",
    updatedAt: "2023-04-24T14:54:32.615Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clguylspy002l010j7bpah611",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:21.575Z",
    updatedAt: "2023-04-24T14:54:21.575Z",
    checksData:
      '{"done":25,"error":0,"loading":0,"pending":0,"total":25,"featureUnlicensed":0}',
    id: "clguylk7b0028010j1byyudhl",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:20.535Z",
    updatedAt: "2023-04-24T14:54:20.535Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clguyljee000l010jtpvy2opo",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-24T14:54:20.262Z",
    updatedAt: "2023-04-24T14:54:20.262Z",
    checksData:
      '{"done":18,"error":0,"loading":0,"pending":0,"total":18,"featureUnlicensed":0}',
    id: "clguylj6t000b010jcceknloq",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001 involving user ludving.russich",
    tags: '["user:privileged"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:16.302Z",
    updatedAt: "2023-04-23T20:00:16.302Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgtu344s009v01x1yymcwp35",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:15.831Z",
    updatedAt: "2023-04-23T20:00:15.831Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgtu33rr009f01x1ekq378pq",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:15.608Z",
    updatedAt: "2023-04-23T20:00:15.608Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgtu33lh009801x1vshlmp1p",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:15.227Z",
    updatedAt: "2023-04-23T20:00:15.227Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgtu33ay008q01x1czu1irli",
    status: "open",
    title: "OFFICE 365 ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:15.004Z",
    updatedAt: "2023-04-23T20:00:15.004Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgtu334r008j01x1fdf0v2ik",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:09.531Z",
    updatedAt: "2023-04-23T20:00:09.531Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgtu2ywo003j01z7tb0flbxz",
    status: "open",
    title: "OFFICE 365 [Tor Failed Login]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T20:00:09.140Z",
    updatedAt: "2023-04-23T20:00:09.140Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgtu2ylq003b01z7wnr5kepo",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:32.140Z",
    updatedAt: "2023-04-23T16:00:32.140Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgtlit8r00o001x1b2rnsbs6",
    status: "open",
    title: "OFFICE 365 [Brute Force Attempt by IP]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:23.523Z",
    updatedAt: "2023-04-23T16:00:23.523Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgtlimle00le01x1x33xqlkm",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:23.018Z",
    updatedAt: "2023-04-23T16:00:23.018Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgtlim7d00ky01x1qz35bqus",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:18.747Z",
    updatedAt: "2023-04-23T16:00:18.747Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clgtliiwo00j301x1ag7a010m",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:18.521Z",
    updatedAt: "2023-04-23T16:00:18.521Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgtliiqf00iw01x1psb4y4pp",
    status: "open",
    title: "Look-alike Domain of demo.com registered",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:18.336Z",
    updatedAt: "2023-04-23T16:00:18.336Z",
    checksData:
      '{"done":14,"error":0,"loading":0,"pending":0,"total":14,"featureUnlicensed":0}',
    id: "clgtliilb00iq01x1lndnkkki",
    status: "open",
    title:
      "Found impossible travel for user alte.bekante involving countries CN HK",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: "obi.wan@redcarbon.ai",
    createdAt: "2023-04-23T16:00:18.047Z",
    updatedAt: "2023-04-23T16:00:18.047Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgtliida00ii01x1b9ozythg",
    status: "under_investigation",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:17.803Z",
    updatedAt: "2023-04-23T16:00:17.803Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgtlii6h00i801x1deb2yfh2",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:17.350Z",
    updatedAt: "2023-04-23T16:00:17.350Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgtlihtx00hv01x10bfus5q1",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:17.027Z",
    updatedAt: "2023-04-23T16:00:17.027Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgtlihky00hi01x149525q8d",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:09.454Z",
    updatedAt: "2023-04-23T16:00:09.454Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgtlibql006p01z7vt68j5jg",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:06.907Z",
    updatedAt: "2023-04-23T16:00:06.907Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgtli9ru00b701x1dyof87vg",
    status: "open",
    title:
      "'Large Upload (HTTPS)' generated by XDR Analytics detected on host ludving.russich001 involving user ludving.russich001\\ludving.russich001",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T16:00:06.528Z",
    updatedAt: "2023-04-23T16:00:06.528Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgtli9hb00au01x196yf1br0",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001 involving user ludving.russich",
    tags: '["user:privileged"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:20.682Z",
    updatedAt: "2023-04-23T12:00:20.682Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgtcxxah00es01z7eol9aqtk",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:18.018Z",
    updatedAt: "2023-04-23T12:00:18.018Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgtcxv8h00cx01z7clcsn304",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: "yoda@redcarbon.ai",
    createdAt: "2023-04-23T12:00:17.814Z",
    updatedAt: "2023-04-23T12:00:17.814Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgtcxv2t00cq01z74zanyy5t",
    status: "closed",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:16.800Z",
    updatedAt: "2023-04-23T12:00:16.800Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgtcxuan00b701z7lgwfx46f",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:11.913Z",
    updatedAt: "2023-04-23T12:00:11.913Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgtcxqix00ds01x1um6i0k8r",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:11.677Z",
    updatedAt: "2023-04-23T12:00:11.677Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgtcxqcd00di01x1tdiicpvg",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T12:00:11.313Z",
    updatedAt: "2023-04-23T12:00:11.313Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgtcxq2900d501x1ven0bdt7",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:13.979Z",
    updatedAt: "2023-04-23T08:00:13.979Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgt4d50a003v01z7k9p68g93",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: "yoda@redcarbon.ai",
    createdAt: "2023-04-23T08:00:13.753Z",
    updatedAt: "2023-04-23T08:00:13.753Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgt4d4u0003n01z7g46g68vo",
    status: "closed",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:13.379Z",
    updatedAt: "2023-04-23T08:00:13.379Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgt4d4jm003701z7kiy8tkr0",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:13.116Z",
    updatedAt: "2023-04-23T08:00:13.116Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgt4d4ca002p01z7jfrsp719",
    status: "open",
    title: "OFFICE 365 [Tor Failed Login]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:12.917Z",
    updatedAt: "2023-04-23T08:00:12.917Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgt4d46t002h01z7fmt3t1tj",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:12.727Z",
    updatedAt: "2023-04-23T08:00:12.727Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clgt4d41j002b01z7caoklvis",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:12.540Z",
    updatedAt: "2023-04-23T08:00:12.540Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgt4d3wc002401z7a7p4qtfq",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:12.289Z",
    updatedAt: "2023-04-23T08:00:12.289Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgt4d3pb001u01z70ea9gxux",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:11.926Z",
    updatedAt: "2023-04-23T08:00:11.926Z",
    checksData:
      '{"done":14,"error":0,"loading":0,"pending":0,"total":14,"featureUnlicensed":0}',
    id: "clgt4d3fa001h01z7wg9r535y",
    status: "open",
    title:
      "Found impossible travel for user alte.bekante involving countries CN HK",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:11.724Z",
    updatedAt: "2023-04-23T08:00:11.724Z",
    checksData:
      '{"done":16,"error":0,"loading":0,"pending":0,"total":16,"featureUnlicensed":0}',
    id: "clgt4d39m001901z74kc338zx",
    status: "open",
    title:
      "'Uncommon PowerShell commands used to create or alter scheduled task parameters' generated by XDR Analytics BIOC detected on host SAP0002 involving user SYSTEM",
    tags: "[]",
    severity: 30,
  },
  {
    assignee: "yoda@redcarbon.ai",
    createdAt: "2023-04-23T08:00:11.413Z",
    updatedAt: "2023-04-23T08:00:11.413Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgt4d310000y01z7b1i4loww",
    status: "closed",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:11.137Z",
    updatedAt: "2023-04-23T08:00:11.137Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgt4d2tc000o01z72icid8fl",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T08:00:10.928Z",
    updatedAt: "2023-04-23T08:00:10.928Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgt4d2nj001l01x1wl6ppkny",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:33.787Z",
    updatedAt: "2023-04-23T04:00:33.787Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgsvsx6i001o01z7wxwcm3l8",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:32.256Z",
    updatedAt: "2023-04-23T04:00:32.256Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgsvsvzz001g01z7a4yl48o8",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:21.200Z",
    updatedAt: "2023-04-23T04:00:21.200Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgsvsngu001b01z7o0lu5giz",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:16.537Z",
    updatedAt: "2023-04-23T04:00:16.537Z",
    checksData:
      '{"done":14,"error":0,"loading":0,"pending":0,"total":14,"featureUnlicensed":0}',
    id: "clgsvsjvb000y01z7wmrt532l",
    status: "open",
    title:
      "Found impossible travel for user alte.bekante involving countries CN HK",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:14.289Z",
    updatedAt: "2023-04-23T04:00:14.289Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgsvsi4x003q01x1mj3zrj1w",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:12.736Z",
    updatedAt: "2023-04-23T04:00:12.736Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgsvsgxj000q01z7vhfkiu9i",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:12.487Z",
    updatedAt: "2023-04-23T04:00:12.487Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgsvsgqv001v01x1x81jjojm",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T04:00:12.246Z",
    updatedAt: "2023-04-23T04:00:12.246Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgsvsgk5001l01x1eyjtr9l4",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T00:00:22.096Z",
    updatedAt: "2023-04-23T00:00:22.096Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgsn8108003101z7dzadke0t",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T00:00:19.084Z",
    updatedAt: "2023-04-23T00:00:19.084Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgsn7yq3001g01x1kajiwev1",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T00:00:18.935Z",
    updatedAt: "2023-04-23T00:00:18.935Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgsn7ylz001e01z7pnqjaiq3",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T00:00:18.803Z",
    updatedAt: "2023-04-23T00:00:18.803Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgsn7yia001801x1mufxskwl",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-23T00:00:18.417Z",
    updatedAt: "2023-04-23T00:00:18.417Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgsn7y7l000w01x1petg6kni",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged","XDR DAILY SCAN"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:18.361Z",
    updatedAt: "2023-04-22T20:00:18.361Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgsenb20007r01x1fowifq1q",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:18.180Z",
    updatedAt: "2023-04-22T20:00:18.180Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgsenawz007k01x1b6roomed",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:18.002Z",
    updatedAt: "2023-04-22T20:00:18.002Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgsenas2007e01x1mmld2pz7",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:17.771Z",
    updatedAt: "2023-04-22T20:00:17.771Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgsenalm007401x17m2y5pki",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:16.956Z",
    updatedAt: "2023-04-22T20:00:16.956Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgsen9z0006p01z7btr3dchj",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:16.421Z",
    updatedAt: "2023-04-22T20:00:16.421Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgsen9k4006901z7mq71rurx",
    status: "open",
    title: "OFFICE 365 [Tor Failed Login]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:16.135Z",
    updatedAt: "2023-04-22T20:00:16.135Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgsen9c7006101z74nbu78qq",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:13.956Z",
    updatedAt: "2023-04-22T20:00:13.956Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgsen7nn004601z7ppiqgmtf",
    status: "open",
    title:
      "'MVPower DVR Shell Unauthenticated Command Execution Vulnerability' generated by PAN NGFW detected on host 192.168.230.50",
    tags: "[]",
    severity: 10,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:13.676Z",
    updatedAt: "2023-04-22T20:00:13.676Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgsen7fv003v01z7xplavvd5",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:13.259Z",
    updatedAt: "2023-04-22T20:00:13.259Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgsen74a003i01z7hwensxzv",
    status: "open",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: "yoda@redcarbon.ai",
    createdAt: "2023-04-22T20:00:12.496Z",
    updatedAt: "2023-04-22T20:00:12.496Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgsen6j4000r01x13hzysn59",
    status: "closed",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T20:00:11.033Z",
    updatedAt: "2023-04-22T20:00:11.033Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgsen5eg000h01x14qisaahd",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:21.452Z",
    updatedAt: "2023-04-22T16:00:21.452Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgs62qbv003201z7czbxv6oe",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:19.907Z",
    updatedAt: "2023-04-22T16:00:19.907Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgs62p4y001801z75jit4nwe",
    status: "open",
    title: "OFFICE 365 [Allowed Phish]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:14.837Z",
    updatedAt: "2023-04-22T16:00:14.837Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgs62l85002401x1d3k9kytz",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:14.206Z",
    updatedAt: "2023-04-22T16:00:14.206Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgs62kqm001b01x1h5rc3tsi",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:13.886Z",
    updatedAt: "2023-04-22T16:00:13.886Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgs62khp000t01x1fzd4a5fz",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:09.554Z",
    updatedAt: "2023-04-22T16:00:09.554Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgs62h5e001101z7lcm7wwuf",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:09.345Z",
    updatedAt: "2023-04-22T16:00:09.345Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgs62gzl000u01z7h8k4drit",
    status: "open",
    title: "OFFICE 365 ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:09.106Z",
    updatedAt: "2023-04-22T16:00:09.106Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgs62gsx000n01z7bx88shzp",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:09.061Z",
    updatedAt: "2023-04-22T16:00:09.061Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgs62gro000o01x1t51p3f4c",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:08.817Z",
    updatedAt: "2023-04-22T16:00:08.817Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgs62gkx000b01z7vzd9dj4i",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001 involving user ludving.russich",
    tags: '["user:privileged"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T16:00:08.787Z",
    updatedAt: "2023-04-22T16:00:08.787Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgs62gk2000b01x139ulbl8g",
    status: "open",
    title:
      "'Large Upload (HTTPS)' generated by XDR Analytics detected on host ludving.russich001 involving user ludving.russich001\\ludving.russich001",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:18.150Z",
    updatedAt: "2023-04-22T12:00:18.150Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgrxi0o5000z01x1g34ubdkh",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:17.868Z",
    updatedAt: "2023-04-22T12:00:17.868Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrxi0gb000p01x16wkyb86h",
    status: "open",
    title: "OFFICE 365 ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:14.607Z",
    updatedAt: "2023-04-22T12:00:14.607Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrxhxxq002d01z7sce5klau",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:14.408Z",
    updatedAt: "2023-04-22T12:00:14.408Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgrxhxs8002601z7lefbbxzm",
    status: "open",
    title:
      "'MVPower DVR Shell Unauthenticated Command Execution Vulnerability' generated by PAN NGFW detected on host 192.168.230.50",
    tags: "[]",
    severity: 10,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:14.150Z",
    updatedAt: "2023-04-22T12:00:14.150Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgrxhxl1001v01z7gkqvib0n",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:10.762Z",
    updatedAt: "2023-04-22T12:00:10.762Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgrxhuyy000i01x1bdzwiio8",
    status: "open",
    title:
      "'Large Upload (Generic)' generated by XDR Analytics detected on host 192.168.107.33",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T12:00:10.541Z",
    updatedAt: "2023-04-22T12:00:10.541Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgrxhuss000801x1nqvwo6xt",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:22.342Z",
    updatedAt: "2023-04-22T08:00:22.342Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgroxgsm006h01z7sxmtu16l",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:22.056Z",
    updatedAt: "2023-04-22T08:00:22.056Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgroxgkn006b01z7qhk42jhg",
    status: "open",
    title: "FIREEYE NX ALERT [SmartVision-Event]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:21.651Z",
    updatedAt: "2023-04-22T08:00:21.651Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgroxg9f006301z794lrqfdk",
    status: "open",
    title: "Look-alike Domain of demo.com registered",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:21.357Z",
    updatedAt: "2023-04-22T08:00:21.357Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgroxg17005x01z70e19wubm",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:14.343Z",
    updatedAt: "2023-04-22T08:00:14.343Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgroxamf005401x19tnq9ath",
    status: "open",
    title: "OFFICE 365 [Brute Force Attempt by IP]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:13.659Z",
    updatedAt: "2023-04-22T08:00:13.659Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgroxa3f002i01x1hoqkiag2",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:13.385Z",
    updatedAt: "2023-04-22T08:00:13.385Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrox9vs002001x13lhbokke",
    status: "open",
    title: "OFFICE 365 [Allowed Phish]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:13.200Z",
    updatedAt: "2023-04-22T08:00:13.200Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgrox9qn001t01x1yeeyx5rn",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:13.010Z",
    updatedAt: "2023-04-22T08:00:13.010Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgrox9ld001o01x1asmb1559",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T08:00:12.762Z",
    updatedAt: "2023-04-22T08:00:12.762Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgrox9eh001b01x1ck56mt6f",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:20.598Z",
    updatedAt: "2023-04-22T04:00:20.598Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgrgcsc6003p01x1hftlsgxu",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:20.368Z",
    updatedAt: "2023-04-22T04:00:20.368Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgrgcs5s003h01x1tdgm2rur",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:20.065Z",
    updatedAt: "2023-04-22T04:00:20.065Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrgcrxd002z01x1z127v503",
    status: "open",
    title: "OFFICE 365 [Allowed Phish]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:19.872Z",
    updatedAt: "2023-04-22T04:00:19.872Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgrgcrrz002s01x18s2itean",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:19.582Z",
    updatedAt: "2023-04-22T04:00:19.582Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgrgcrjy002f01x1mkhs6vi4",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:12.649Z",
    updatedAt: "2023-04-22T04:00:12.649Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrgcm7d003x01z7v6n4ulvv",
    status: "open",
    title: "OFFICE 365 [Brute Force Attempt by IP]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:09.797Z",
    updatedAt: "2023-04-22T04:00:09.797Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgrgck04001b01z7cuxwk1ir",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:09.407Z",
    updatedAt: "2023-04-22T04:00:09.407Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgrgcjpa001401z7z7knqfd4",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:09.317Z",
    updatedAt: "2023-04-22T04:00:09.317Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgrgcjmt002201x18jbmg2ts",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:08.848Z",
    updatedAt: "2023-04-22T04:00:08.848Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgrgcj9s000y01z7v6fu2ij6",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:08.546Z",
    updatedAt: "2023-04-22T04:00:08.546Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgrgcj1d000t01z7rwgzov6v",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:08.418Z",
    updatedAt: "2023-04-22T04:00:08.418Z",
    checksData:
      '{"done":19,"error":0,"loading":0,"pending":0,"total":19,"featureUnlicensed":0}',
    id: "clgrgcixm000f01x1yx6x1h34",
    status: "open",
    title:
      "'Local Analysis Malware' generated by XDR Agent detected on host alte-laptop involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:06.950Z",
    updatedAt: "2023-04-22T04:00:06.950Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgrgcht1000j01z7r2v5ii1c",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T04:00:06.539Z",
    updatedAt: "2023-04-22T04:00:06.539Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgrgchhm000601z7a5qgjcar",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:21.163Z",
    updatedAt: "2023-04-22T00:00:21.163Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgr7s5nu00bo01z7hp5e8o8k",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:20.908Z",
    updatedAt: "2023-04-22T00:00:20.908Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgr7s5gs00bg01z743mxnnaj",
    status: "open",
    title: "OFFICE 365 [Tor Authenticated Activity]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:20.429Z",
    updatedAt: "2023-04-22T00:00:20.429Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgr7s53g00ay01z7m3ziqi5f",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:20.062Z",
    updatedAt: "2023-04-22T00:00:20.062Z",
    checksData:
      '{"done":16,"error":0,"loading":0,"pending":0,"total":16,"featureUnlicensed":0}',
    id: "clgr7s4t900ao01z7812tpvz5",
    status: "open",
    title:
      "'Uncommon PowerShell commands used to create or alter scheduled task parameters' generated by XDR Analytics BIOC detected on host SAP0002 involving user SYSTEM",
    tags: "[]",
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:19.641Z",
    updatedAt: "2023-04-22T00:00:19.641Z",
    checksData:
      '{"done":11,"error":0,"loading":0,"pending":0,"total":11,"featureUnlicensed":0}',
    id: "clgr7s4hk00ad01z7fky9st4m",
    status: "open",
    title:
      'Found impossible travel for user marcos.borsos involving countries "IT - CH"',
    tags: '["user:executive"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:19.326Z",
    updatedAt: "2023-04-22T00:00:19.326Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgr7s48t00a501z7ak0vdwlx",
    status: "open",
    title:
      "'Large Upload (HTTPS)' generated by XDR Analytics detected on host ludving.russich001 involving user ludving.russich001\\ludving.russich001",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:19.036Z",
    updatedAt: "2023-04-22T00:00:19.036Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgr7s40r009s01z78fl3j5mw",
    status: "open",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-22T00:00:17.966Z",
    updatedAt: "2023-04-22T00:00:17.966Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgr7s371008901z721xnet76",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["XDR DAILY SCAN","user:privileged"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:23.421Z",
    updatedAt: "2023-04-21T16:00:23.421Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgqqmx6k008i01z71bpprjna",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:23.045Z",
    updatedAt: "2023-04-21T16:00:23.045Z",
    checksData:
      '{"done":14,"error":0,"loading":0,"pending":0,"total":14,"featureUnlicensed":0}',
    id: "clgqqmww4008d01z7zswch4sj",
    status: "open",
    title:
      "Found impossible travel for user alte.bekante involving countries CN HK",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:15.017Z",
    updatedAt: "2023-04-21T16:00:15.017Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clgqqmqp4002v01x1426ex98y",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:14.704Z",
    updatedAt: "2023-04-21T16:00:14.704Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgqqmqgf002o01x1nohdd6fp",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:14.313Z",
    updatedAt: "2023-04-21T16:00:14.313Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgqqmq5j002e01x1i97iiunb",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:13.900Z",
    updatedAt: "2023-04-21T16:00:13.900Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgqqmpu2002101x1bbq5hcgl",
    status: "open",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:12.561Z",
    updatedAt: "2023-04-21T16:00:12.561Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgqqmosw002201z75mnzb3iw",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T16:00:12.455Z",
    updatedAt: "2023-04-21T16:00:12.455Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgqqmopy000i01x1iqnu7mhl",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:49.536Z",
    updatedAt: "2023-04-21T12:00:49.536Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgqi2u7z00t301z7svcthlco",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:47.402Z",
    updatedAt: "2023-04-21T12:00:47.402Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgqi2skp00sn01z7p8xclg0b",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:25.008Z",
    updatedAt: "2023-04-21T12:00:25.008Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgqi2ban00md01z7lrz8fjlq",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["XDR DAILY SCAN","user:privileged"]',
    severity: 90,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:18.617Z",
    updatedAt: "2023-04-21T12:00:18.617Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgqi26d300ec01x1sftovakj",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:18.245Z",
    updatedAt: "2023-04-21T12:00:18.245Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgqi262r00e401x1apsu21v0",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:17.887Z",
    updatedAt: "2023-04-21T12:00:17.887Z",
    checksData:
      '{"done":16,"error":0,"loading":0,"pending":0,"total":16,"featureUnlicensed":0}',
    id: "clgqi25su00dx01x11r4x88mm",
    status: "open",
    title:
      "'Uncommon PowerShell commands used to create or alter scheduled task parameters' generated by XDR Analytics BIOC detected on host SAP0002 involving user SYSTEM",
    tags: "[]",
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T12:00:17.414Z",
    updatedAt: "2023-04-21T12:00:17.414Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgqi25fp00dm01x1xqqkb29n",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:21.151Z",
    updatedAt: "2023-04-21T08:00:21.151Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgq9hl7i00g901z7g0ahytqb",
    status: "open",
    title: "OFFICE 365 [Brute Force Attempt by IP]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:20.321Z",
    updatedAt: "2023-04-21T08:00:20.321Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgq9hkkh00dn01z7xr5gc0ay",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:20.105Z",
    updatedAt: "2023-04-21T08:00:20.105Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgq9hkeh00dg01z76q6atlre",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:19.879Z",
    updatedAt: "2023-04-21T08:00:19.879Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgq9hk8600da01z7zrbgaojx",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:18.154Z",
    updatedAt: "2023-04-21T08:00:18.154Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgq9hiw900bf01z7u3o613yv",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:17.978Z",
    updatedAt: "2023-04-21T08:00:17.978Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgq9hird00ba01z7r7wwjjty",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:17.690Z",
    updatedAt: "2023-04-21T08:00:17.690Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgq9hijd00ax01z7vxeltqag",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T08:00:17.443Z",
    updatedAt: "2023-04-21T08:00:17.443Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgq9hici00ak01z7rq068meq",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:11.991Z",
    updatedAt: "2023-04-21T04:00:11.991Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgq0wr1300bf01z7bvix93i1",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:11.755Z",
    updatedAt: "2023-04-21T04:00:11.755Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgq0wqui00b801z7mzvj8f3z",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:10.290Z",
    updatedAt: "2023-04-21T04:00:10.290Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgq0wppt006v01x1pjwb2af0",
    status: "open",
    title: "OFFICE 365 [Allowed Phish]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:09.922Z",
    updatedAt: "2023-04-21T04:00:09.922Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgq0wpfl006o01x19i3wjkh0",
    status: "open",
    title: "FIREEYE NX ALERT [SmartVision-Event]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:08.026Z",
    updatedAt: "2023-04-21T04:00:08.026Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgq0wnyq009d01z7bfb956my",
    status: "open",
    title:
      "'Large Upload (HTTPS)' generated by XDR Analytics detected on host ludving.russich001 involving user ludving.russich001\\ludving.russich001",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T04:00:07.454Z",
    updatedAt: "2023-04-21T04:00:07.454Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgq0wnj1009001z7eai2nciy",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:54.184Z",
    updatedAt: "2023-04-21T00:24:54.184Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7vl3001001z7ybcvewxo",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:54.001Z",
    updatedAt: "2023-04-21T00:24:54.001Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7vg0000v01z7ct9pg098",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:54.001Z",
    updatedAt: "2023-04-21T00:24:54.001Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7vg0000i01x1wh73eu83",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.830Z",
    updatedAt: "2023-04-21T00:24:53.830Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7vba000q01z7amvxaaqw",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.830Z",
    updatedAt: "2023-04-21T00:24:53.830Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7vba000d01x1lep1iy0f",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.666Z",
    updatedAt: "2023-04-21T00:24:53.666Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7v6p000l01z7ctsmp4rk",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.666Z",
    updatedAt: "2023-04-21T00:24:53.666Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7v6p000801x11dbf4r0d",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.490Z",
    updatedAt: "2023-04-21T00:24:53.490Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7v1t000301x1ub78cmqb",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:24:53.490Z",
    updatedAt: "2023-04-21T00:24:53.490Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpt7v1t000g01z7aoc38tbd",
    status: "open",
    title:
      "Found a possible MITRE tactics correlation within multiple incidents involving marcos.borsos on 4 incidents",
    tags: '["user:executive"]',
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:00:19.281Z",
    updatedAt: "2023-04-21T00:00:19.281Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgpsc9jl007b01z768hgkreu",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:privileged"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:00:19.088Z",
    updatedAt: "2023-04-21T00:00:19.088Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpsc9e8007401z78gclen51",
    status: "open",
    title: "OFFICE 365 [Tor Failed Login]",
    tags: "[]",
    severity: 0,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:00:18.846Z",
    updatedAt: "2023-04-21T00:00:18.846Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgpsc97i006w01z7ld7x2eo8",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:00:18.598Z",
    updatedAt: "2023-04-21T00:00:18.598Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgpsc90l006q01z7kwdr7df0",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-21T00:00:18.382Z",
    updatedAt: "2023-04-21T00:00:18.382Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgpsc8um006l01z762g4tlqs",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:27.327Z",
    updatedAt: "2023-04-20T20:00:27.327Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgpjrsn2007301z7tomwu7zb",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:27.112Z",
    updatedAt: "2023-04-20T20:00:27.112Z",
    checksData:
      '{"done":8,"error":0,"loading":0,"pending":0,"total":8,"featureUnlicensed":0}',
    id: "clgpjrsh2006w01z7wek9p87u",
    status: "open",
    title:
      "'Failed Connections' generated by XDR Analytics detected on host 192.168.107.12",
    tags: "[]",
    severity: 45,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:26.814Z",
    updatedAt: "2023-04-20T20:00:26.814Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgpjrs8t006m01z7u8sttrvj",
    status: "open",
    title:
      "10 'Local Analysis Malware' alerts detected by XDR Agent on host alte-laptop  involving user alte.bekante",
    tags: '["host:it","host:workstation"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:18.415Z",
    updatedAt: "2023-04-20T20:00:18.415Z",
    checksData:
      '{"done":4,"error":0,"loading":0,"pending":0,"total":4,"featureUnlicensed":0}',
    id: "clgpjrlri00r901x1zpki99ig",
    status: "open",
    title: "WINDOWS METHODOLOGY [Group Add - Administrators]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:18.182Z",
    updatedAt: "2023-04-20T20:00:18.182Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgpjrll000r401x1owvhrsrz",
    status: "open",
    title: "OFFICE 365 ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:17.851Z",
    updatedAt: "2023-04-20T20:00:17.851Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgpjrlbu00qx01x109lvql89",
    status: "open",
    title:
      "'MVPower DVR Shell Unauthenticated Command Execution Vulnerability' generated by PAN NGFW detected on host 192.168.230.50",
    tags: "[]",
    severity: 10,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:16.531Z",
    updatedAt: "2023-04-20T20:00:16.531Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgpjrkb300qm01x1t720iz6t",
    status: "open",
    title:
      "'MySQL MaxDB Webtool HTTP Request Parsing Buffer Overflow Vulnerability' generated by PAN NGFW detected on host serverDAHLIA002 involving user francois.dahlia",
    tags: "[]",
    severity: 15,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:14.414Z",
    updatedAt: "2023-04-20T20:00:14.414Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgpjrinn005301z7r2ujr6g5",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001 involving user ludving.russich",
    tags: '["user:privileged"]',
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T20:00:13.081Z",
    updatedAt: "2023-04-20T20:00:13.081Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgpjrhn900q901x15rnyrst7",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:19.505Z",
    updatedAt: "2023-04-20T16:00:19.505Z",
    checksData:
      '{"done":21,"error":0,"loading":0,"pending":0,"total":21,"featureUnlicensed":0}',
    id: "clgpb6zhs005p01x1llnwjbve",
    status: "open",
    title: "OFFICE 365 [Suspicious File Type Uploaded]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:18.926Z",
    updatedAt: "2023-04-20T16:00:18.926Z",
    checksData:
      '{"done":6,"error":0,"loading":0,"pending":0,"total":6,"featureUnlicensed":0}',
    id: "clgpb6z1p005901x1n9ktjd3a",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force Success]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:18.677Z",
    updatedAt: "2023-04-20T16:00:18.677Z",
    checksData:
      '{"done":15,"error":0,"loading":0,"pending":0,"total":15,"featureUnlicensed":0}',
    id: "clgpb6yuq005201x1nqm1j5yu",
    status: "open",
    title: "FIREEYE ENDPOINT [Malware Prevented: generic.mg.29230c2cf5981e79]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:18.319Z",
    updatedAt: "2023-04-20T16:00:18.319Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgpb6ykv004s01x1rdruwe4l",
    status: "open",
    title:
      "'New Administrative Behavior' generated by XDR Analytics detected on host joe-ropes-POS1 involving user joe.ropes",
    tags: '["user:privileged"]',
    severity: 55,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:17.917Z",
    updatedAt: "2023-04-20T16:00:17.917Z",
    checksData:
      '{"done":16,"error":0,"loading":0,"pending":0,"total":16,"featureUnlicensed":0}',
    id: "clgpb6y9p004f01x1vxvyq8fn",
    status: "open",
    title:
      "'Uncommon PowerShell commands used to create or alter scheduled task parameters' generated by XDR Analytics BIOC detected on host SAP0002 involving user SYSTEM",
    tags: "[]",
    severity: 30,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:17.551Z",
    updatedAt: "2023-04-20T16:00:17.551Z",
    checksData:
      '{"done":20,"error":0,"loading":0,"pending":0,"total":20,"featureUnlicensed":0}',
    id: "clgpb6xzj004401x1x0v7e0cs",
    status: "open",
    title:
      "'LOLBIN connecting to a rare host' generated by XDR Analytics BIOC detected on host alte-laptop involving user alte-laptop\\aless",
    tags: '["host:it","host:workstation"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:11.011Z",
    updatedAt: "2023-04-20T16:00:11.011Z",
    checksData:
      '{"done":24,"error":0,"loading":0,"pending":0,"total":24,"featureUnlicensed":0}',
    id: "clgpb6sxu003r01x1ptx3z5i4",
    status: "open",
    title:
      "4 'Local Analysis Malware' alerts prevented by XDR Agent on 4 hosts  involving 4 users",
    tags: '["host:it","host:workstation"]',
    severity: 70,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T16:00:09.015Z",
    updatedAt: "2023-04-20T16:00:09.015Z",
    checksData:
      '{"done":12,"error":0,"loading":0,"pending":0,"total":12,"featureUnlicensed":0}',
    id: "clgpb6ree002401x1m5dxvcyl",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:35.774Z",
    updatedAt: "2023-04-20T12:00:35.774Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgp2moxp00be01z7numqih5h",
    status: "open",
    title: "OFFICE 365 [Brute Force Attempt by IP]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:32.315Z",
    updatedAt: "2023-04-20T12:00:32.315Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgp2mm9l008s01z7axjqjxws",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:31.398Z",
    updatedAt: "2023-04-20T12:00:31.398Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgp2mlk5008k01z7p2o6awyj",
    status: "open",
    title: "WINDOWS ANALYTICS [Brute Force]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:31.120Z",
    updatedAt: "2023-04-20T12:00:31.120Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgp2mlcd008e01z7ryqf4tiw",
    status: "open",
    title: "FIREEYE NX ALERT [SmartVision-Event]",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:30.652Z",
    updatedAt: "2023-04-20T12:00:30.652Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgp2mkzf008601z7dg596szv",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:30.426Z",
    updatedAt: "2023-04-20T12:00:30.426Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgp2mkt4007z01z7vmd4wm69",
    status: "open",
    title: "OFFICE 365 ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:30.100Z",
    updatedAt: "2023-04-20T12:00:30.100Z",
    checksData:
      '{"done":5,"error":0,"loading":0,"pending":0,"total":5,"featureUnlicensed":0}',
    id: "clgp2mkk3007s01z7pyfth0r3",
    status: "open",
    title: "Look-alike Domain of demo.com registered",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:29.816Z",
    updatedAt: "2023-04-20T12:00:29.816Z",
    checksData:
      '{"done":14,"error":0,"loading":0,"pending":0,"total":14,"featureUnlicensed":0}',
    id: "clgp2mkc7007m01z7knf720ot",
    status: "open",
    title:
      "Found impossible travel for user alte.bekante involving countries CN HK",
    tags: "[]",
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T12:00:18.843Z",
    updatedAt: "2023-04-20T12:00:18.843Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgp2mbvc001b01z70kcmuxk9",
    status: "open",
    title:
      "'WildFire Malware' generated by XDR Agent detected on host ludving.russich001",
    tags: '["user:privileged"]',
    severity: 100,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T08:00:24.606Z",
    updatedAt: "2023-04-20T08:00:24.606Z",
    checksData:
      '{"done":17,"error":0,"loading":0,"pending":0,"total":17,"featureUnlicensed":0}',
    id: "clgou1t7h01bu01z7dv3jzg3i",
    status: "open",
    title: "WINDOWS METHODOLOGY [Suspicious DCSync]",
    tags: '["user:privileged"]',
    severity: 50,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T08:00:09.978Z",
    updatedAt: "2023-04-20T08:00:09.978Z",
    checksData:
      '{"done":13,"error":0,"loading":0,"pending":0,"total":13,"featureUnlicensed":0}',
    id: "clgou1hx601r301x1ufoko6bc",
    status: "open",
    title: "OFFICE 365 [Malware Detected]",
    tags: "[]",
    severity: 20,
  },
  {
    assignee: null,
    createdAt: "2023-04-20T08:00:09.660Z",
    updatedAt: "2023-04-20T08:00:09.660Z",
    checksData:
      '{"done":9,"error":0,"loading":0,"pending":0,"total":9,"featureUnlicensed":0}',
    id: "clgou1ho701qv01x1rtnzxosj",
    status: "open",
    title: "VPN ANALYTICS [Abnormal Logon]",
    tags: '["user:executive"]',
    severity: 80,
  },
];
